name: Node.js CI

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test

  summary:
    name: Commit Info Summary
    runs-on: ubuntu-latest
    needs: [lint, build, test]

    steps:
      - uses: actions/checkout@v4
      - name: Display Commit Info
        run: |
          echo "### ✅ Build Successful!" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit ID:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Auteur:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(git log -1 --format=%cd)" >> $GITHUB_STEP_SUMMARY